theme = "rose_pine_moon"

[editor]
true-color = true
color-modes = true
bufferline = "multiple"
default-yank-register = "+"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
y = ["yank_main_selection_to_clipboard", "normal_mode"]
