add_newline = true

format = """
$directory\
$git_branch\
$line_break\

$character"""

[directory]
format = "[$path]($style) "
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

