add_newline = true

format = """
$directory\
$git_branch\
$cmd_duration\
$line_break\

$character"""

[directory]
format = "[$path]($style) "

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

vimcmd_symbol = "[❮](purple)"


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

