set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on

# Change prefix to Ctrl+a
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Config reloading
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

# Split window, new pane in the current directory
unbind %
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Vim-style pane switching
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim-style pane switching without prefix (Alt)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Change base index from 0 to 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Switch window with Shift+arrows
bind -n S-Left previous-window
bind -n S-Right next-window

# Select window with Alt+number
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Resize panes
bind -r Left  resize-pane -L 5
bind -r Right resize-pane -R 5
bind -r Up    resize-pane -U 5
bind -r Down  resize-pane -D 5

#
unbind -T copy-mode-vi MouseDragEnd1Pane

gray='#44475a'
# Custom theme
set -g status "on"
set -g status-bg "black"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"
set -g pane-border-style "fg=${gray}"
set -g pane-active-border-style "fg=magenta"
set -g window-status-activity-style "fg=white,bg=blue,none"
set -g window-status-separator ""
set -g window-status-style "fg=white,bg=${gray},none"
set -g message-style "fg=cyan,bg=${gray},align=centre"
set -g message-command-style "fg=cyan,bg=black,align=centre"
set -g window-status-current-format "#[fg=cyan,bg=black] #I: #[fg=magenta,bg=black](✓) #[fg=blue,bg=black]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #[fg=pink,bg=black]"
set -g window-status-format "#[fg=cyan,bg=black] #I #[fg=white,bg=black]#W"
set -g status-right "#[fg=black,bg=cyan]  #[fg=white,bg=${gray}] #W #{?client_prefix,#[bg=magenta],#[bg=green]}#[fg=black]  #[fg=white,bg=${gray}] #{session_name} "
set -g status-left ""

