# Set terminal with proper colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

# Enable mouse support
set -g mouse on

# Diable right click menu
unbind -T root MouseDown3Pane

# Enable clipboard integration
set -g set-clipboard on

# Change prefix to Ctrl + a
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Allow config reloading using prefix + r
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf \; display-message "Config reloaded."

# Rebind vertical window split (new pane in the current dir)
unbind %
bind | split-window -h -c "#{pane_current_path}"

# Allow pane navigation with Alt + hjkl (Vim-style)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Start window numbering at 1 instead of 0
set -g base-index 1

# Start pane number at 1 instead of 0
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# Renumber windows automatically when one closes
set-option -g renumber-windows on

# Allow window switching with Shift + arrow keys
bind -n S-Left  previous-window
bind -n S-Right next-window

# Allow window selecting with Alt + number
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4

# Set status line position
set -g status "on"
set -g status-position top

# Status bar style
set -g status-style bg=default,fg=black,bright
set -g status-left ""
set -g status-right "#[fg=black,bright]#S"

# Window status style
set -g window-status-format "■"
set -g window-status-current-format "■"
set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=magenta\#,nobold}"
set -g window-status-current-bell-style "fg=red,nobold"

# Set border style
set -g pane-active-border-style fg=magenta
