# Set terminal with proper colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

# Enable mouse support
set -g mouse on

# Enable clipboard integration
set -g set-clipboard on

# Change prefix to Ctrl + a
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Allow config reloading using prefix + r
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

# Rebind vertical window split (new pane in the current dir)
unbind %
bind | split-window -h -c "#{pane_current_path}"

# Rebind horizontal window split (new pane in the current dir)
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Allow pane navigation with prefix + hjkl (Vim-style)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Allow pane navigation with Alt instead of prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Start window numbering at 1 instead of 0
set -g base-index 1

# Start pane number at 1 instead of 0
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# Renumber windows automatically when one closes
set-option -g renumber-windows on

# Allow window switching with Shift + arrow keys
bind -n S-Left  previous-window
bind -n S-Right next-window

# Allow window selecting with Alt + number
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Allow pane resizing with prefix + arrow keys
bind -r Left  resize-pane -L 5
bind -r Right resize-pane -R 5
bind -r Up    resize-pane -U 5
bind -r Down  resize-pane -D 5

# Set status line position
set -g status "on"
set -g status-position top

# Replace the status line by a rectangle with a terminal icon
# -> The rectangle's background color will change when using prefix.
# -> Colors used are from Dracula theme.
bg_color="#282a36"
gray_color='#44475a'
term_icon=""
set -g status-bg "${bg_color}"
set -g status-right "#{?client_prefix,#[bg=magenta],#[bg=blue]}#[fg=black] ${term_icon} "
set -g status-left ""

# Set pane borders colors
set -g pane-border-style "fg=${gray_color}"
set -g pane-active-border-style "fg=magenta"

# Hide window list
set -g window-status-current-format ""
set -g window-status-format ""

# Set status line message style
set -g message-style "fg=yellow,bg=${gray_color},align=centre"
set -g message-command-style "fg=cyan,bg=black,align=centre"

